language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=coverage.out

after_success:
  - include_cov=coverage.out bash <(curl -s https://codecov.io/bash)
