language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
- go test -v -coverprofile=coverage.coverprofile
- gover
- goveralls -coverprofile=gover.coverprofile -service travis-ci
