name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download
      run: |
          go mod download

    - name: Lint
      run: |
          ./scripts/lint.sh

    - name: Build
      run: |
          go build -v

    - name: Coverage
      run: |
          go test -covermode=atomic -coverprofile=coverage.txt .
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
          #verbose: true # optional (default = false)
